# Exercises in Classification II

## Exercise 1

In this exercise, we will use the titanic dataset to build different classifiers for the target variable `Survived`. In this exercise, all the necessary steps are broken down into small individual task you should do. Note that the first 6 tasks are the same as Exercise 1 from last time, so you can just copy-paste your code from that notebook. Do the following tasks:

1. Load in the titanic dataset (on Moodle as "titanic_survival_data.csv"), select the columns "Pclass", "Sex", "Age", and "Fare" for the feature set X and "Survived" for the target variable y.
2. For the columns "Age" and "Fare", replace the missing values with the column's mean.
3. Turn the variables "Pclass" and "Sex" into dummy variables.
4. Do a train-test split of the data with 20% for testing. Use random state 962.
5. Scale the X training dataset, using the standard scaler.
6. Transform the X test dataset with the same scaler fitted in task 5.
7. Train a decision tree model on the data with "Survived" as the response variable.
8. Create the confusion matrix and calculate, accuracy precision recall, and f-1 score for this model.
9. Train simple Random Forest, AdaBoost, and XGBoost models on the data with "Survived" as the response variable.
10. Create the confusion matrix and calculate, accuracy precision recall, and f-1 score for the above models.
11. Use a sampling technique (under, over or SMOTE) to improve either the Random Forest, AdaBoost, or XGBoost model. Create the confusion matrix and calculate, accuracy precision recall, and f-1 score for the new model.
12. Due hyper-parameter tuning to improve the above model. Create the confusion matrix and calculate, accuracy precision recall, and f-1 score for the new model.

In [13]:
import pandas as pd

# Load the Titanic dataset
titanic_data = pd.read_csv('titanic_survival_data.csv')

# Selecting relevant columns: "Pclass", "Sex", "Age", "Fare", and "Survived"
X = titanic_data[['Pclass', 'Sex', 'Age', 'Fare']]
y = titanic_data['Survived']

In [14]:
# Replacing missing values in "Age" and "Fare" with the mean of the respective column
X['Age'].fillna(X['Age'].mean(), inplace=True)
X['Fare'].fillna(X['Fare'].mean(), inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_1656\30683637.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  X['Age'].fillna(X['Age'].mean(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_1656\30683637.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an 

0        7.250
1      712.833
2        7.925
3       53.100
4        8.050
        ...   
886     13.000
887     30.000
888     23.450
889     30.000
890      7.750
Name: Fare, Length: 891, dtype: float64

In [17]:
# Convert the categorical variables "Pclass" and "Sex" into dummy variables
X_dummies = pd.get_dummies(X, columns=['Pclass', 'Sex'], drop_first=True)


In [19]:
from sklearn.model_selection import train_test_split

# Perform the train-test split with 20% for testing and random_state 962
X_train, X_test, y_train, y_test = train_test_split(X_dummies, y, test_size=0.2, random_state=962)

In [22]:
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Scale the X_train dataset
X_train_scaled = scaler.fit_transform(X_train)

# Transform the X_test dataset using the same scaler
X_test_scaled = scaler.transform(X_test)

In [31]:
# Step 1: After scaling the data
scaler = StandardScaler()

# Scale the X_train dataset
X_train_scaled = scaler.fit_transform(X_train)

# Transform the X_test dataset using the same scaler
X_test_scaled = scaler.transform(X_test)

# Step 2: Check the shapes and missing values
import numpy as np

# Check for missing values in the scaled training and test sets
missing_values_train = np.isnan(X_train_scaled).sum()
missing_values_test = np.isnan(X_test_scaled).sum()

print(f"Missing values in training data: {missing_values_train}")
print(f"Missing values in testing data: {missing_values_test}")

# Step 3: If NaN values are found, apply the imputer
from sklearn.impute import SimpleImputer

if missing_values_train > 0 or missing_values_test > 0:
    # Reapply imputation
    imputer = SimpleImputer(strategy='mean')
    X_train_scaled = imputer.fit_transform(X_train_scaled)
    X_test_scaled = imputer.transform(X_test_scaled)

# Step 4: Check the shapes of X_train_scaled and X_test_scaled to ensure alignment
print("Shape of X_train_scaled:", X_train_scaled.shape)
print("Shape of X_test_scaled:", X_test_scaled.shape)

# Step 5: Now proceed with model training (e.g., AdaBoost)
ab_model = AdaBoostClassifier(random_state=962)
ab_model.fit(X_train_scaled, y_train)
y_pred_ab = ab_model.predict(X_test_scaled)

# Evaluate the model's performance
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

conf_matrix_ab = confusion_matrix(y_test, y_pred_ab)
accuracy_ab = accuracy_score(y_test, y_pred_ab)
precision_ab = precision_score(y_test, y_pred_ab)
recall_ab = recall_score(y_test, y_pred_ab)
f1_ab = f1_score(y_test, y_pred_ab)

print("AdaBoost Confusion Matrix:\n", conf_matrix_ab)
print("AdaBoost Accuracy: ", accuracy_ab)
print("AdaBoost Precision: ", precision_ab)
print("AdaBoost Recall: ", recall_ab)
print("AdaBoost F1 Score: ", f1_ab)

Missing values in training data: 156
Missing values in testing data: 44
Shape of X_train_scaled: (712, 5)
Shape of X_test_scaled: (179, 5)
AdaBoost Confusion Matrix:
 [[91 18]
 [14 56]]
AdaBoost Accuracy:  0.8212290502793296
AdaBoost Precision:  0.7567567567567568
AdaBoost Recall:  0.8
AdaBoost F1 Score:  0.7777777777777778


In [29]:
# Check for missing values in the scaled training and test sets
import numpy as np

# Check if there are any NaN values in the scaled training and test sets
missing_values_train = np.isnan(X_train_scaled).sum()
missing_values_test = np.isnan(X_test_scaled).sum()

print(f"Missing values in training data: {missing_values_train}")
print(f"Missing values in testing data: {missing_values_test}")

Missing values in training data: 156
Missing values in testing data: 44


In [27]:
# After scaling X_train_scaled and X_test_scaled, handle any missing values

from sklearn.impute import SimpleImputer

# Check for missing values in the dataset
missing_values = pd.DataFrame(X_train_scaled).isnull().sum()
print("Missing values in training set:", missing_values)

# If there are any missing values, impute them with the mean
imputer = SimpleImputer(strategy='mean')

# Fit and transform the training data
X_train_imputed = imputer.fit_transform(X_train_scaled)

# Transform the test data using the same imputer
X_test_imputed = imputer.transform(X_test_scaled)

# Now, train the AdaBoost model with the imputed data
from sklearn.ensemble import AdaBoostClassifier

ab_model = AdaBoostClassifier(random_state=962)
ab_model.fit(X_train_imputed, y_train)

# Make predictions on the test data
y_pred_ab = ab_model.predict(X_test_imputed)

# Evaluate AdaBoost model performance
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

conf_matrix_ab = confusion_matrix(y_test, y_pred_ab)
accuracy_ab = accuracy_score(y_test, y_pred_ab)
precision_ab = precision_score(y_test, y_pred_ab)
recall_ab = recall_score(y_test, y_pred_ab)
f1_ab = f1_score(y_test, y_pred_ab)

print("AdaBoost Confusion Matrix:\n", conf_matrix_ab)
print("AdaBoost Accuracy: ", accuracy_ab)
print("AdaBoost Precision: ", precision_ab)
print("AdaBoost Recall: ", recall_ab)
print("AdaBoost F1 Score: ", f1_ab)

Missing values in training set: 0    136
1     20
2      0
3      0
4      0
dtype: int64
AdaBoost Confusion Matrix:
 [[91 18]
 [14 56]]
AdaBoost Accuracy:  0.8212290502793296
AdaBoost Precision:  0.7567567567567568
AdaBoost Recall:  0.8
AdaBoost F1 Score:  0.7777777777777778


In [23]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Initialize the Decision Tree classifier
dt_model = DecisionTreeClassifier(random_state=962)

# Train the model on the scaled training data
dt_model.fit(X_train_scaled, y_train)

# Make predictions on the test data
y_pred_dt = dt_model.predict(X_test_scaled)

# Evaluate the model's performance
conf_matrix = confusion_matrix(y_test, y_pred_dt)
accuracy = accuracy_score(y_test, y_pred_dt)
precision = precision_score(y_test, y_pred_dt)
recall = recall_score(y_test, y_pred_dt)
f1 = f1_score(y_test, y_pred_dt)

print("Confusion Matrix:\n", conf_matrix)
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1)

Confusion Matrix:
 [[92 17]
 [17 53]]
Accuracy:  0.8100558659217877
Precision:  0.7571428571428571
Recall:  0.7571428571428571
F1 Score:  0.7571428571428571


In [32]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
import xgboost as xgb

# Train Random Forest model
rf_model = RandomForestClassifier(random_state=962)
rf_model.fit(X_train_scaled, y_train)
y_pred_rf = rf_model.predict(X_test_scaled)

# Train AdaBoost model
ab_model = AdaBoostClassifier(random_state=962)
ab_model.fit(X_train_scaled, y_train)
y_pred_ab = ab_model.predict(X_test_scaled)

# Train XGBoost model
xgb_model = xgb.XGBClassifier(random_state=962)
xgb_model.fit(X_train_scaled, y_train)
y_pred_xgb = xgb_model.predict(X_test_scaled)

# Evaluate Random Forest model
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)

# Evaluate AdaBoost model
conf_matrix_ab = confusion_matrix(y_test, y_pred_ab)
accuracy_ab = accuracy_score(y_test, y_pred_ab)
precision_ab = precision_score(y_test, y_pred_ab)
recall_ab = recall_score(y_test, y_pred_ab)
f1_ab = f1_score(y_test, y_pred_ab)

# Evaluate XGBoost model
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test, y_pred_xgb)
recall_xgb = recall_score(y_test, y_pred_xgb)
f1_xgb = f1_score(y_test, y_pred_xgb)

# Print performance metrics for all models
print("Random Forest Confusion Matrix:\n", conf_matrix_rf)
print("Random Forest Accuracy: ", accuracy_rf)
print("Random Forest Precision: ", precision_rf)
print("Random Forest Recall: ", recall_rf)
print("Random Forest F1 Score: ", f1_rf)

print("\nAdaBoost Confusion Matrix:\n", conf_matrix_ab)
print("AdaBoost Accuracy: ", accuracy_ab)
print("AdaBoost Precision: ", precision_ab)
print("AdaBoost Recall: ", recall_ab)
print("AdaBoost F1 Score: ", f1_ab)

print("\nXGBoost Confusion Matrix:\n", conf_matrix_xgb)
print("XGBoost Accuracy: ", accuracy_xgb)
print("XGBoost Precision: ", precision_xgb)
print("XGBoost Recall: ", recall_xgb)
print("XGBoost F1 Score: ", f1_xgb)

Random Forest Confusion Matrix:
 [[98 11]
 [17 53]]
Random Forest Accuracy:  0.8435754189944135
Random Forest Precision:  0.828125
Random Forest Recall:  0.7571428571428571
Random Forest F1 Score:  0.7910447761194029

AdaBoost Confusion Matrix:
 [[91 18]
 [14 56]]
AdaBoost Accuracy:  0.8212290502793296
AdaBoost Precision:  0.7567567567567568
AdaBoost Recall:  0.8
AdaBoost F1 Score:  0.7777777777777778

XGBoost Confusion Matrix:
 [[96 13]
 [19 51]]
XGBoost Accuracy:  0.8212290502793296
XGBoost Precision:  0.796875
XGBoost Recall:  0.7285714285714285
XGBoost F1 Score:  0.7611940298507462


In [34]:
from imblearn.over_sampling import SMOTE

# Initialize SMOTE for balancing the classes in the training set
smote = SMOTE(random_state=962)

# Apply SMOTE to the training data
X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

# Train Random Forest model with SMOTE
rf_smote_model = RandomForestClassifier(random_state=962)
rf_smote_model.fit(X_train_smote, y_train_smote)
y_pred_rf_smote = rf_smote_model.predict(X_test_scaled)

# Evaluate Random Forest model with SMOTE
conf_matrix_rf_smote = confusion_matrix(y_test, y_pred_rf_smote)
accuracy_rf_smote = accuracy_score(y_test, y_pred_rf_smote)
precision_rf_smote = precision_score(y_test, y_pred_rf_smote)
recall_rf_smote = recall_score(y_test, y_pred_rf_smote)
f1_rf_smote = f1_score(y_test, y_pred_rf_smote)

# Print the performance metrics for the SMOTE Random Forest model
print("\nRandom Forest with SMOTE Confusion Matrix:\n", conf_matrix_rf_smote)
print("Random Forest with SMOTE Accuracy: ", accuracy_rf_smote)
print("Random Forest with SMOTE Precision: ", precision_rf_smote)
print("Random Forest with SMOTE Recall: ", recall_rf_smote)
print("Random Forest with SMOTE F1 Score: ", f1_rf_smote)


Random Forest with SMOTE Confusion Matrix:
 [[94 15]
 [18 52]]
Random Forest with SMOTE Accuracy:  0.8156424581005587
Random Forest with SMOTE Precision:  0.7761194029850746
Random Forest with SMOTE Recall:  0.7428571428571429
Random Forest with SMOTE F1 Score:  0.7591240875912408


In [35]:
# Load the adult dataset
adult_data = pd.read_csv('adult.csv')

# Check the first few rows of the dataset
adult_data.head()

# Clean the 'income' variable so that it has only two values: '<=50K' and '>50K'
adult_data['income'] = adult_data['income'].replace({' <=50K': '0', ' >50K': '1'})

# Check the unique values of the 'income' column after cleaning
print(adult_data['income'].unique())

# Select a minimum set of feature variables you want to use for predicting 'income'
X = adult_data[['age', 'education', 'hours-per-week']]  # Example feature variables
y = adult_data['income']  # Target variable

# Check the shape of the selected features and target
print(X.shape, y.shape)

<StringArray>
['<=50K', '>50K', '<=50K.', '>50K.']
Length: 4, dtype: str
(48842, 3) (48842,)


In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Function to evaluate the model's performance
def evaluate_model(y_test, y_pred):
    # Calculate confusion matrix and other metrics
    conf_matrix = confusion_matrix(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    
    # Print the evaluation metrics
    print("Confusion Matrix:\n", conf_matrix)
    print("Accuracy: ", accuracy)
    print("Precision: ", precision)
    print("Recall: ", recall)
    print("F1 Score: ", f1)
    
    return conf_matrix, accuracy, precision, recall, f1

In [38]:
from sklearn.model_selection import GridSearchCV

# Hyperparameter grid for Random Forest
param_grid_rf = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

# Initialize GridSearchCV for Random Forest
grid_search_rf = GridSearchCV(estimator=RandomForestClassifier(random_state=962),
                              param_grid=param_grid_rf,
                              cv=5, scoring='accuracy')

# Fit GridSearchCV on the training data
grid_search_rf.fit(X_train_scaled, y_train)

# Best parameters found for Random Forest
best_params_rf = grid_search_rf.best_params_

# Train the model using the best parameters
best_rf_model = grid_search_rf.best_estimator_

# Evaluate the best Random Forest model
y_pred_best_rf = best_rf_model.predict(X_test_scaled)

# Performance metrics for the best model
print("\nBest Random Forest Model Performance:")
evaluate_model(y_test, y_pred_best_rf)


Best Random Forest Model Performance:
Confusion Matrix:
 [[99 10]
 [19 51]]
Accuracy:  0.8379888268156425
Precision:  0.8360655737704918
Recall:  0.7285714285714285
F1 Score:  0.7786259541984732


(array([[99, 10],
        [19, 51]]),
 0.8379888268156425,
 0.8360655737704918,
 0.7285714285714285,
 0.7786259541984732)

## Exercise 2

In this exercise, we will predict the two income classes in the adult dataset (The file "adult.csv" is also on Moodle). 

Answer the following questions:
1. Clean the `income` variable such that it has only two values (for instance by using `str.replace` to remover the `.`).
2. Select as set of minimum two feature variables you want to use to predict `income`. Do the necessary transformation of these variables.
3. Create X and y dataset and split the datasets into training and testing sets
4. Train a KNN classifier to predict the variable `income` based on the feature variables selected in 2 - try out some different Ks 
5. Train a logistic regression classifier to predict the variable `income` based on the feature variables selected in 2 and compare it to the KNN classifier.
6. Train a decision tree classifier to predict the variable `income` based on the feature variables selected in 2 and compare it to the previous classifiers.
7. Train a random forest classifier to predict the variable `income` based on the feature variables selected in 2 and compare it to the previous classifiers.
8. Train a AdaBoost classifier to predict the variable `income` based on the feature variables selected in 2 and compare it to the previous classifiers.
9. (Optional) Can you improve any of the models by balancing the `income` variable?

In [39]:
# Load the adult dataset
adult_data = pd.read_csv('adult.csv')

# Clean the 'income' variable so that it has only two values: '<=50K' and '>50K'
adult_data['income'] = adult_data['income'].replace({' <=50K': '0', ' >50K': '1'})

# Check the unique values of 'income' after cleaning
print(adult_data['income'].unique())

<StringArray>
['<=50K', '>50K', '<=50K.', '>50K.']
Length: 4, dtype: str


In [40]:
# Selecting features and target
X = adult_data[['age', 'hours-per-week']]  # Features
y = adult_data['income']  # Target variable

In [41]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=962)

In [43]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, confusion_matrix

# Try different Ks (k = 3, 5, 7)
knn = KNeighborsClassifier(n_neighbors=5)  # You can change this to try different values for k
knn.fit(X_train, y_train)

# Make predictions on the test data
y_pred_knn = knn.predict(X_test)

# Evaluate KNN performance
print("\nKNN Classifier Performance:")
conf_matrix = confusion_matrix(y_test, y_pred_knn)
accuracy = accuracy_score(y_test, y_pred_knn)
precision = precision_score(y_test, y_pred_knn, average='micro')  # or 'macro' or 'weighted'
recall = recall_score(y_test, y_pred_knn, average='micro')
f1 = f1_score(y_test, y_pred_knn, average='micro')

# Print the evaluation metrics
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1)


KNN Classifier Performance:
Confusion Matrix:
 [[3538  978  404   73]
 [1729  451  207   41]
 [ 977  238  295   73]
 [ 497  109  123   36]]
Accuracy:  0.44221517043709696
Precision:  0.44221517043709696
Recall:  0.44221517043709696
F1 Score:  0.44221517043709696


In [44]:
from sklearn.linear_model import LogisticRegression

# Train a Logistic Regression classifier
log_reg_model = LogisticRegression(random_state=962)
log_reg_model.fit(X_train, y_train)

# Make predictions on the test data
y_pred_log_reg = log_reg_model.predict(X_test)

# Evaluate Logistic Regression performance
print("\nLogistic Regression Performance:")
conf_matrix = confusion_matrix(y_test, y_pred_log_reg)
accuracy = accuracy_score(y_test, y_pred_log_reg)
precision = precision_score(y_test, y_pred_log_reg, average='micro')
recall = recall_score(y_test, y_pred_log_reg, average='micro')
f1 = f1_score(y_test, y_pred_log_reg, average='micro')

# Print the evaluation metrics
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1)


Logistic Regression Performance:
Confusion Matrix:
 [[4823    0  170    0]
 [2324    0  104    0]
 [1441    0  142    0]
 [ 690    0   75    0]]
Accuracy:  0.5082403521343024
Precision:  0.5082403521343024
Recall:  0.5082403521343024
F1 Score:  0.5082403521343024


In [45]:
from sklearn.tree import DecisionTreeClassifier

# Train a Decision Tree classifier
dt_model = DecisionTreeClassifier(random_state=962)
dt_model.fit(X_train, y_train)

# Make predictions on the test data
y_pred_dt = dt_model.predict(X_test)

# Evaluate Decision Tree performance
print("\nDecision Tree Performance:")
conf_matrix = confusion_matrix(y_test, y_pred_dt)
accuracy = accuracy_score(y_test, y_pred_dt)
precision = precision_score(y_test, y_pred_dt, average='micro')
recall = recall_score(y_test, y_pred_dt, average='micro')
f1 = f1_score(y_test, y_pred_dt, average='micro')

# Print the evaluation metrics
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1)


Decision Tree Performance:
Confusion Matrix:
 [[4419  226  309   39]
 [2156   96  151   25]
 [1172   54  346   11]
 [ 577   24  146   18]]
Accuracy:  0.499436994574675
Precision:  0.499436994574675
Recall:  0.499436994574675
F1 Score:  0.499436994574675


In [46]:
from sklearn.ensemble import RandomForestClassifier

# Train a Random Forest classifier
rf_model = RandomForestClassifier(random_state=962)
rf_model.fit(X_train, y_train)

# Make predictions on the test data
y_pred_rf = rf_model.predict(X_test)

# Evaluate Random Forest performance
print("\nRandom Forest Performance:")
conf_matrix = confusion_matrix(y_test, y_pred_rf)
accuracy = accuracy_score(y_test, y_pred_rf)
precision = precision_score(y_test, y_pred_rf, average='micro')
recall = recall_score(y_test, y_pred_rf, average='micro')
f1 = f1_score(y_test, y_pred_rf, average='micro')

# Print the evaluation metrics
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1)


Random Forest Performance:
Confusion Matrix:
 [[4351  262  329   51]
 [2113  113  169   33]
 [1146   53  363   21]
 [ 559   30  157   19]]
Accuracy:  0.4960589620227249
Precision:  0.4960589620227249
Recall:  0.4960589620227249
F1 Score:  0.4960589620227249


In [47]:
from sklearn.ensemble import AdaBoostClassifier

# Train an AdaBoost classifier
ab_model = AdaBoostClassifier(random_state=962)
ab_model.fit(X_train, y_train)

# Make predictions on the test data
y_pred_ab = ab_model.predict(X_test)

# Evaluate AdaBoost performance
print("\nAdaBoost Performance:")
conf_matrix = confusion_matrix(y_test, y_pred_ab)
accuracy = accuracy_score(y_test, y_pred_ab)
precision = precision_score(y_test, y_pred_ab, average='micro')
recall = recall_score(y_test, y_pred_ab, average='micro')
f1 = f1_score(y_test, y_pred_ab, average='micro')

# Print the evaluation metrics
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1)


AdaBoost Performance:
Confusion Matrix:
 [[4993    0    0    0]
 [2428    0    0    0]
 [1583    0    0    0]
 [ 765    0    0    0]]
Accuracy:  0.5111065615723206
Precision:  0.5111065615723206
Recall:  0.5111065615723206
F1 Score:  0.5111065615723206


In [48]:
from imblearn.over_sampling import SMOTE

# Initialize SMOTE for balancing the classes in the training set
smote = SMOTE(random_state=962)

# Apply SMOTE to the training data
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

# Train a Random Forest model with SMOTE
rf_smote_model = RandomForestClassifier(random_state=962)
rf_smote_model.fit(X_train_smote, y_train_smote)

# Make predictions on the test data
y_pred_rf_smote = rf_smote_model.predict(X_test)

# Evaluate Random Forest with SMOTE performance
print("\nRandom Forest with SMOTE Performance:")
conf_matrix = confusion_matrix(y_test, y_pred_rf_smote)
accuracy = accuracy_score(y_test, y_pred_rf_smote)
precision = precision_score(y_test, y_pred_rf_smote, average='micro')
recall = recall_score(y_test, y_pred_rf_smote, average='micro')
f1 = f1_score(y_test, y_pred_rf_smote, average='micro')

# Print the evaluation metrics
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1)


Random Forest with SMOTE Performance:
Confusion Matrix:
 [[1596 1288  910 1199]
 [ 765  614  455  594]
 [ 176  157  563  687]
 [  91   66  251  357]]
Accuracy:  0.32040126932132257
Precision:  0.32040126932132257
Recall:  0.32040126932132257
F1 Score:  0.32040126932132257
